name: Build 64tass

on:
  workflow_dispatch:

jobs:
  build-64tass:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            binary_name: 64tass
            platform_name: Linux
          #- os: windows-latest
          #  binary_name: 64tass.exe
          #  platform_name: Windows
          - os: macos-latest
            binary_name: 64tass
            platform_name: Darwin

    steps:
      - uses: actions/checkout@v4

      - name: Build 64tass
        working-directory: ./external-sources/64tass
        shell: bash
        run: |
          make
          mkdir -p ../../bins/${{ matrix.platform_name }}
          cp ${{ matrix.binary_name }} ../../bins/${{ matrix.platform_name }}/

      - name: Upload platform binary
        uses: actions/upload-artifact@v4
        with:
          name: 64tass-${{ matrix.platform_name }}
          path: bins/${{ matrix.platform_name }}/${{ matrix.binary_name }}
          retention-days: 90

      - name: Upload all binaries
        uses: actions/upload-artifact@v4
        with:
          name: 64tass-all-platforms
          path: bins/
          retention-days: 90