name: Build 64tass

on:
  workflow_dispatch:

jobs:
  build-64tass:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            binary_name: 64tass
            copy_bins_cmd: mkdir -p ../../bins/${{ runner.os }} && cp 64tass ../../bins/${{ runner.os }}/
          - os: windows-latest
            binary_name: 64tass.exe
            copy_bins_cmd: mkdir ..\\..\\bins\\${{ runner.os }} 2>NUL & copy 64tass.exe ..\\..\\bins\\${{ runner.os }}\\
          - os: macos-latest
            binary_name: 64tass
            copy_bins_cmd: mkdir -p ../../bins/${{ runner.os }} && cp 64tass ../../bins/${{ runner.os }}/

    steps:
      - uses: actions/checkout@v4

      - name: Build 64tass
        working-directory: ./external-sources/64tass
        run: |
          make
          ${{ matrix.copy_bins_cmd }}

      - name: Upload platform binary
        uses: actions/upload-artifact@v4
        with:
          name: 64tass-${{ runner.os }}
          path: bins/${{ runner.os }}/${{ matrix.binary_name }}
          retention-days: 90

      - name: Upload all binaries
        uses: actions/upload-artifact@v4
        with:
          name: 64tass-all-platforms
          path: bins/
          retention-days: 90