name: Create Release

on:
  workflow_dispatch:
  
permissions:
  contents: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: animation-tool-ubuntu-latest
          path: dist/ubuntu
          repository: muhmi/c64-anim-tool
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download MacOS artifact
        uses: actions/download-artifact@v4
        with:
          name: animation-tool-macos-latest
          path: dist/macos
          repository: muhmi/c64-anim-tool
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ steps.timestamp.outputs.timestamp }}
          name: Release ${{ steps.timestamp.outputs.timestamp }}
          files: |
            dist/ubuntu/*
            dist/macos/*
          generate_release_notes: true